# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'examples/*'
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'fast.gemspec'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

Metrics/ModuleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
