# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'examples/*'
  TargetRubyVersion: 2.6

Layout/LineLength:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false


Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'fast.gemspec'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

Metrics/ModuleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
